export const subjectOptions = [
  { value: "all", label: "주제 없음" },
  { value: "", label: "--------- 노인정 주제 ---------", disabled: true },
  { value: "economy", label: "경제" },
  { value: "historicalRemains", label: "고적" },
  { value: "industry", label: "공업" },
  { value: "education", label: "교육" },
  { value: "transportation", label: "교통" },
  { value: "language", label: "언어" },
  { value: "", label: "--------- 어인정 주제 ---------", disabled: true },
  { value: "snack", label: "간식" },
  { value: "localAttractionsAndFestivals", label: "국내 관광지 / 축제" },
  { value: "localTVShows", label: "국내 방송 프로그램" },
  { value: "construction", label: "국가지정문화재" },
  { value: "companyAndBrand", label: "기업 / 브랜드" },
  { value: "kkutu", label: "끄투코리아" },
  { value: "animalCrossing", label: "동물의 숲" },
  { value: "litenovel", label: "라이트 노벨" },
  { value: "lostArk", label: "로스트아크" },
  { value: "blueArchive", label: "블루 아카이브" },
  { value: "THE_iDOLM@STER", label: "아이돌마스터" },
  { value: "unesco", label: "유네스코 유산" },
  { value: "Yu-Gi-Oh", label: "유희왕" },
];
